### PR TITLE
fix #121

### LINKED ISSUE #121: exception on circle E-Mail share
Error: OCA\Files_DownloadLimit\Db\LimitMapper::get(): Argument #1 ($token) must be of type string, null given, called in /var/www/html/nextcloud/apps/files_downloadlimit/lib/Listener/BeforeTemplateRenderedListener.php on line 57 in file '/var/www/html/nextcloud/apps/files_downloadlimit/lib/Db/LimitMapper.php' line 36

### PR DESCRIPTION
**Pull request by Superjamp**
add Throwable to catch error

Signed-off-by: Sebastian Biller <s.biller@tu-braunschweig.de>

### CODE REVIEW

File: lib/Listener/BeforeTemplateRenderedListener.php [hunk 1]
```diff
@@ -58,7 +58,10 @@ public function handle(Event $event): void {
 		} catch (\Exception $e) {
 			// No limits are set, ignoring...
 			return;
-		}
+		} catch (\Throwable $e) {
+                        // No limits are set, ignoring...
+                        return;
+                }
```
Comment (skjnldsv) [inline lib/Listener/BeforeTemplateRenderedListener.php:64]:
```suggestion
		} catch (\Throwable $e) {
			// No limits are set, ignoring...
			return;
		}
```
