### PR TITLE
fix: keep track of download count

### LINKED ISSUE #501: File Download limit not decreasing
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Create an external share and set download limit
2. Open the external share link in a private/incognito browser window.
3. Download the shared file.
4. Observe the download limit value.

### Expected behaviour
The download limit should decrease by one with each file download, reflecting the number of downloads remaining.

### Actual behaviour
The download limit remains unchanged after each download, regardless of how many times the file is accessed.

### Server configuration

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud version:** 31.0.6

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Browser

**Browser name:** Firefox/Chrome/Safari/…

**Browser version:** 124/125/…

**Operating system:** Windows/Ubuntu/Mac/…

<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

### PR DESCRIPTION
**Pull request by hamza221**
fix #501

implemented https://github.com/nextcloud/files_downloadlimit/issues/501#issuecomment-3132109688 which worked like a charm

### CODE REVIEW

File: lib/Listener/BeforeNodeReadListener.php [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+			return;
+		}
+
+		/** @var ISharedStorage $storage */
+		$share = $storage->getShare();
+
+		if ($share->getShareType() !== IShare::TYPE_LINK) {
+			return;
+		}
+
```
Comment (come-nc) [inline lib/Listener/BeforeNodeReadListener.php:99]: The check for range requests and cache is missing, that means when playing a video it will count as a download for each request.
I think we should have here the same thing as activity to only count one download for a video play.

**Comment by hamza221** [comment]
> as

Ui exits, but there's a bug and its unusable atm

**Review by come-nc — APPROVED** [review]
